spring:
   profiles:
     active:
     - dev
---
spring:
 profiles: dev #开发环境
   name: microservice-config-atyillion-dev

---
spring:
  profiles: test #测试环境
  application:
    name: microservicecloud-config-atguigu-test